### ISSUE TITLE
OPE evaluation 

### ISSUE THREAD

**Issue by g-zin** [abnerwang/py-Vital#1]
Thank you very much for your work. 
But when I evaluate VITAL tracker on many datasets tb50,tb100,otb13
the overlap and precision are always less than MDNet tracker. 
could you know the reason? 
I really appreciate your answer

**Comment by abnerwang** [comment]
> Thank you very much for your work.
> But when I evaluate VITAL tracker on many datasets tb50,tb100,otb13
> the overlap and precision are always less than MDNet tracker.
> could you know the reason?
> I really appreciate your answer

First you may need to pretrain the model on your own machine, then in the tracking phase you need to adjust the parameters according to the actual situations. In some cases, you may only need to adjust the `maxiter_g` parameter.

**Comment by mengmeng18** [comment]
good job!

**Comment by g-zin** [comment]
> > Thank you very much for your work.
> > But when I evaluate VITAL tracker on many datasets tb50,tb100,otb13
> > the overlap and precision are always less than MDNet tracker.
> > could you know the reason?
> > I really appreciate your answer
> 
> First you may need to pretrain the model on your own machine, then in the tracking phase you need to adjust the parameters according to the actual situations. In some cases, you may only need to adjust the `maxiter_g` parameter.

Thank you so much.. I pretrained the model base on 2 dataset ( VOT & imagenet_vid) 
In both cases Vital less than MDNet. 
I notice that in matlab code maxiter_g = 100 
How could I know what parameters that need to modify? (you mean learning_late, w_decay...??) 
Sorry for my question but I am beginner and your answer will help me a lot.

**Comment by abnerwang** [comment]
> > > Thank you very much for your work.
> > > But when I evaluate VITAL tracker on many datasets tb50,tb100,otb13
> > > the overlap and precision are always less than MDNet tracker.
> > > could you know the reason?
> > > I really appreciate your answer
> > 
> > 
> > First you may need to pretrain the model on your own machine, then in the tracking phase you need to adjust the parameters according to the actual situations. In some cases, you may only need to adjust the `maxiter_g` parameter.
> 
> Thank you so much.. I pretrained the model base on 2 dataset ( VOT & imagenet_vid)
> In both cases Vital less than MDNet.
> I notice that in matlab code maxiter_g = 100
> How could I know what parameters that need to modify? (you mean learning_late, w_decay...??)
> Sorry for my question but I am beginner and your answer will help me a lot.

For details about the adjustments, you can search the relevant tutorials online. Did the results of running the MDNet tracker on your own machine reach the accuracy of the authors?

**Comment by g-zin** [comment]
> > > > Thank you very much for your work.
> > > > But when I evaluate VITAL tracker on many datasets tb50,tb100,otb13
> > > > the overlap and precision are always less than MDNet tracker.
> > > > could you know the reason?
> > > > I really appreciate your answer
> > > 
> > > 
> > > First you may need to pretrain the model on your own machine, then in the tracking phase you need to adjust the parameters according to the actual situations. In some cases, you may only need to adjust the `maxiter_g` parameter.
> > 
> > 
> > Thank you so much.. I pretrained the model base on 2 dataset ( VOT & imagenet_vid)
> > In both cases Vital less than MDNet.
> > I notice that in matlab code maxiter_g = 100
> > How could I know what parameters that need to modify? (you mean learning_late, w_decay...??)
> > Sorry for my question but I am beginner and your answer will help me a lot.
> 
> For details about the adjustments, you can search the relevant tutorials online. Did the results of running the MDNet tracker on your own machine reach the accuracy of the authors?

No, but it is close... however Vital's evaluation was much less than the paper.. even less than MDNet.. which it was suppose to improve the results.

**Comment by abnerwang** [comment]
> > > > > Thank you very much for your work.
> > > > > But when I evaluate VITAL tracker on many datasets tb50,tb100,otb13
> > > > > the overlap and precision are always less than MDNet tracker.
> > > > > could you know the reason?
> > > > > I really appreciate your answer
> > > > 
> > > > 
> > > > First you may need to pretrain the model on your own machine, then in the tracking phase you need to adjust the parameters according to the actual situations. In some cases, you may only need to adjust the `maxiter_g` parameter.
> > > 
> > > 
> > > Thank you so much.. I pretrained the model base on 2 dataset ( VOT & imagenet_vid)
> > > In both cases Vital less than MDNet.
> > > I notice that in matlab code maxiter_g = 100
> > > How could I know what parameters that need to modify? (you mean learning_late, w_decay...??)
> > > Sorry for my question but I am beginner and your answer will help me a lot.
> > 
> > 
> > For details about the adjustments, you can search the relevant tutorials online. Did the results of running the MDNet tracker on your own machine reach the accuracy of the authors?
> 
> No, but it is close... however Vital's evaluation was much less than the paper.. even less than MDNet.. which it was suppose to improve the results.

Thank you for your feedback, I will fix the bug as soon as possible. I will notify you in time after the bug is fixed.

**Comment by g-zin** [comment]
Thank you @abnerwang  .. 
I have another question, please. 
In the paper, they mention that they remove G after adversarial learning and during the test phase. 
I couldn't match what write in the paper .. with the code here. 
could you please explain that? 
thank you in advance.

**Comment by abnerwang** [comment]
> Thank you @abnerwang ..
> I have another question, please.
> In the paper, they mention that they remove G after adversarial learning and during the test phase.
> I couldn't match what write in the paper .. with the code here.
> could you please explain that?
> thank you in advance.

I have fixed the bug. You can try again. For the details about Gnet you can read my code. If I have time later, I will write an article about the detailed principles. If you are interested, I will send you a link.

**Comment by abnerwang** [comment]
> Thank you @abnerwang ..
> I have another question, please.
> In the paper, they mention that they remove G after adversarial learning and during the test phase.
> I couldn't match what write in the paper .. with the code here.
> could you please explain that?
> thank you in advance.

If I have time later, I will write an article about the detailed principles. If you are interested, I will send you a link.

**Comment by wysot** [comment]
@abnerwang  
Thank you very much for your work.
the result on OTB2015 is 0.6708, but the result on the paper is 0.68. Can your result reach 0.68?
Thank you in advance.
