### ISSUE TITLE
Excuse me, can this program be executed with cpu?

### ISSUE THREAD

**Issue by wysot** [abnerwang/py-Vital#2]
Excuse me, can this program be executed with cpu?

**Comment by abnerwang** [comment]
No, it must be running on the GPU.

**Comment by abnerwang** [comment]
> Excuse me, can this program be executed with cpu?

No, it must be running on GPU.

**Comment by wysot** [comment]
Thank you, I have another question. I want to know if the model needs pre-training in your code, because I see a folder ‘pretrain’, but the data in this folder is not complete, so the model does not need pre-training? ?



------------------ 原始邮件 ------------------
发件人: "David Wang"<notifications@github.com>;
发送时间: 2019年7月1日(星期一) 晚上6:20
收件人: "abnerwang/py-Vital"<py-Vital@noreply.github.com>;
抄送: "¤光@"<1164639470@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [abnerwang/py-Vital] Excuse me, can this program be executed withcpu? (#2)




No, it must be running on the GPU.

**Comment by wysot** [comment]
In the 'pretain' folder, no opts['lr_decay' is found under the 'options_' file？？



------------------ 原始邮件 ------------------
发件人: "David Wang"<notifications@github.com>;
发送时间: 2019年7月3日(星期三) 晚上6:47
收件人: "abnerwang/py-Vital"<py-Vital@noreply.github.com>;
抄送: "¤光@"<1164639470@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [abnerwang/py-Vital] Excuse me, can this program be executed withcpu? (#2)




Closed #2.
